# Site settings
title: "My GSoC Journey"
email: sidharthmundhra16@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "https://0sidharth.github.io"
title_description: "Hello There! I am Sidharth Mundhra, a second-year undergraduate student pursuing my B.Tech. in Mechanical Engineering from IIT Bombay. Here, I will be blogging about... wait for it... My GSoC Journey!!"
title_image: "https://scontent-bom1-1.xx.fbcdn.net/v/t1.18169-9/14440656_580121552171314_5662860040284597762_n.jpg?_nc_cat=101&ccb=1-3&_nc_sid=09cbfe&_nc_ohc=TY-6PStspbAAX-CwHID&_nc_ht=scontent-bom1-1.xx&oh=cec28b649e80b3502c8e68626628c7b4&oe=60C8DC99"
google_analytics: "UA-20365477-4"
disqus_account: sidharthmundhra
github_repository: https://github.com/0sidharth/0sidharth.github.io
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username:
github_username: 0sidharth
instagram_username:
reddit_username:
linkedin_link: https://www.linkedin.com/in/sidharth-mundhra-9708b0194/
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link: https://www.facebook.com/blankhhh/

# Footer
footer_right: "&lt;/&gt; on <a href=\"https://github.com/0sidharth/0sidharth.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
